### ISSUE TITLE
Firmware 3.0.2 problem with slice command with "timestretched" samples

### ISSUE THREAD

**Issue by ogoshi2000** [Dirtywave/M8Firmware#11]
Since the new firmware update the slice command does not do anything when I put an lfo  (ramp up, retriggered ) on loopstart with loop length = 0. This works in the 2.7.7 firmware.

**Comment by findjonmos** [comment]
Just wondering if the below suggestion helps or solves your issue...?

Instead of using slices when you have your sample timestretched instead for each trigger of the sample use the LT3/4 fx and set its numerical offset to a value that triggers the part of the sample that you want. Be sure to use the correct LT number e.g. if you are using LFO 3 with a ramp up then make sure you use LT3.

Also check that you have the "play" setting of your sampler set to FWDLOOP along with the other settings set as you mentioned
