### ISSUE TITLE
Battery charge and meter issues, again.

### ISSUE THREAD

**Issue by topoexplo** [Dirtywave/M8Firmware#6]
I updated my M8 with the latest firmware when it was first released, and it did seem to improve the battery life initially, but I've noticed in the last few days that my battery dies much quicker now (every 4-5 hrs before and now closer to 2.5-3 hrs.) I also noticed that my battery gauge drops very quickly upon unplugging it from a charger. The battery meter remains on the last quarter charge for most of the time that the M8 is on.

**Comment by trash80** [comment]
You should reach out via support@dirtywave.com instead of the firmware page for troubleshooting.

When you charge it, are you waiting for it to stop animating before using to calculate your hours of use? The battery life varies based on a large amount of circumstances- Idle time, if it's fully charged, screen brightness, speakers vs headphones, etc.

**Comment by topoexplo** [comment]
Sorry about that. I’ll send you an e-mail with more of the specifics.
